### ISSUE TITLE
Only works in simple scenarios

### ISSUE THREAD

**Issue by wtgee** [DavidUnboxed/Ubuntu-20.04-WiFi-RaspberyPi4B#1]
Hey @DavidUnboxed, while I appreciate the documentation about this issue, your solution only "works" because of the `reboot` in `user-data` and in that situation it's bringing up the wireless interface on the second boot, not the first.

Namely, with this solution (or any I have found so far) you **cannot** use the wireless interface to update apt, install additional packages (including changing the ntp client or any other built-in config that will install a package).

There seems to be a bad loop wherein the `wifis` need [`wpasupplicant`](https://netplan.io/reference#properties-for-device-type-wifis) installed in order to work (and `renderer: NetworkManager`), but you cannot install `wpasupplicant` unless you first connect on a wired port.

Hope this helps someone else. And if you figure out a way to get it working on first boot along with more complex installs, please let the world know. Cheers!

**Comment by DavidUnboxed** [comment]
Indeed, I only tested this with the one simple scenario - to get the system up headless reachable via SSH.
